### ISSUE TITLE
Update instructions: always use "cinst metanorma -y" to prevent keep prompting "Yes, No"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/chocolatey-metanorma#12]
Always use "cinst metanorma -y" ("-y" is important!)

**Comment by ronaldtse** [comment]
Yes, and also explain. Thanks!

Is it only with `cinst metanorma -y` or also with `choco install metanorma` ?

**Comment by CAMOBAP795** [comment]
`cinst` is just "alias" for `choco install`, so for silent mode we need: `cinst metanorma -y` or `choco install metanorma -y`

**Comment by CAMOBAP795** [comment]
@ronaldtse I have added commit to https://github.com/riboseinc/chocolatey-metanorma/pull/13

**Comment by CAMOBAP795** [comment]
@ronaldtse done
