### ISSUE TITLE
Use Get-ToolsLocation instead of hard-coded path to Ruby

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/chocolatey-metanorma#6]
From "gep13" a reviewer on Chocolatey:

> gep13 (reviewer) on 20 Dec 2018 08:17:49 +00:00:
>
>I know nothing about this software application, so I can't speak to how it is expected to work, but I don't think hard coding to c:/tools/ruby is a good idea.
>
>First, the end user can change this location through an environment variable which defaults to c:/tools. Have a look at the ruby chocolateyInstall.ps1 file to see how it uses Get-ToolsLocation.

@CAMOBAP795 can you please help fix this? Thanks!

Path: https://chocolatey.org/packages/metanorma/1.0.10

**Comment by CAMOBAP795** [comment]
@ronaldtse sure, it's good suggestion, I will have a look

**Comment by CAMOBAP795** [comment]
@ronaldtse done, can we retag to the same version, AFAIK our release wasn't approved so we can try to submit with the same version

**Comment by ronaldtse** [comment]
Agree, can you go ahead? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse sure, I did small change after CI finished again I will do release

**Comment by ronaldtse** [comment]
Confirmed. Thanks!!
